version: '3.7'

services:
  mytoolsapi:
    build: ./backend
    ports:
      - "5018:5018"
    depends_on:
      - mymongodb
    networks:
      - mytoolsnetwork
  mymongodb:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mytoolsnetwork
  mytoolsfe:
    build: ./frontend
    depends_on:
      - mytoolsapi
    ports:
      - "3000:3000"
    networks:
      - mytoolsnetwork

networks:
    mytoolsnetwork:
        driver: bridge

volumes:
  mongo-data:
